// Generated by: npm run gen:types
// Run that script against your local Supabase instance after any schema change.
// Do not edit manually — your changes will be overwritten.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      items: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          created_at: string;
        };
        Insert: {
          id?: string | undefined;
          user_id: string;
          title: string;
          created_at?: string | undefined;
        };
        Update: {
          id?: string | undefined;
          user_id?: string | undefined;
          title?: string | undefined;
          created_at?: string | undefined;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
